<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>tray_icon.ico</ApplicationIcon>
    <Version>1.3.1</Version>
    <Authors>Aya Yoki (AyaYokiVT) -- Gearlight Labs</Authors>
    <Company>Gearlight Labs</Company>
    <Product>PrivacyWarden</Product>
    <Description>Automated Mullvad VPN manager for VTubers and streamers.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.8" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="tray_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
